name: Publish

inputs: 
  token:
    description: 'npm token used to publish'
    required: true
  node-version:
    default: '18'
    required: false
    description: Node.js version to use

jobs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
      
    - name: Install
      run: yarn

    - name: Build
      run: yarn build

    - name: Set npm token
      run: echo "//registry.npmjs.org/:_authToken=${{ inputs.token }}" > ~/.npmrc

    - name: Publish packages
      run: yarn pub
