name: Publish

inputs: 
  token:
    description: 'npm token used to publish'
    required: true
  node-version:
    default: '18'
    required: false
    description: Node.js version to use

runs:
  using: composite

  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
      
    - name: Install
    	shell: bash
      run: yarn

    - name: Build
    	shell: bash
      run: yarn build

    - name: Set npm token
    	shell: bash
      run: echo "//registry.npmjs.org/:_authToken=${{ inputs.token }}" > ~/.npmrc

    - name: Publish package
    	shell: bash
      run: yarn pub
